/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BankExecutiveRouteImport } from './routes/bank-executive'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EnquiryRouteImport } from './routes/enquiry'
import { Route as LoanServicesRouteImport } from './routes/loan-services'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as OpportunitiesRouteImport } from './routes/opportunities'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedNetworkAdminRouteImport } from './routes/_authenticated/network-admin'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as EnquiryMessagesRouteImport } from './routes/enquiry_.messages'
import { Route as EnquiryProfileRouteImport } from './routes/enquiry_.profile'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as EnquiryMembersIdRouteImport } from './routes/enquiry_.members.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BankExecutiveRoute = BankExecutiveRouteImport.update({
  id: '/bank-executive',
  path: '/bank-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryRoute = EnquiryRouteImport.update({
  id: '/enquiry',
  path: '/enquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanServicesRoute = LoanServicesRouteImport.update({
  id: '/loan-services',
  path: '/loan-services',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesRoute = OpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkAdminRoute =
  AuthenticatedNetworkAdminRouteImport.update({
    id: '/network-admin',
    path: '/network-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const EnquiryMessagesRoute = EnquiryMessagesRouteImport.update({
  id: '/enquiry_/messages',
  path: '/enquiry/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const EnquiryProfileRoute = EnquiryProfileRouteImport.update({
  id: '/enquiry_/profile',
  path: '/enquiry/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnquiryMembersIdRoute = EnquiryMembersIdRouteImport.update({
  id: '/enquiry_/members/$id',
  path: '/enquiry/members/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank-executive': typeof BankExecutiveRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/enquiry': typeof EnquiryRoute
  '/loan-services': typeof LoanServicesRoute
  '/offers': typeof OffersRoute
  '/office': typeof OfficeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payment': typeof PaymentRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/network-admin': typeof AuthenticatedNetworkAdminRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/enquiry/messages': typeof EnquiryMessagesRoute
  '/enquiry/profile': typeof EnquiryProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/enquiry/members/$id': typeof EnquiryMembersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bank-executive': typeof BankExecutiveRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/enquiry': typeof EnquiryRoute
  '/loan-services': typeof LoanServicesRoute
  '/offers': typeof OffersRoute
  '/office': typeof OfficeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payment': typeof PaymentRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/network-admin': typeof AuthenticatedNetworkAdminRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/enquiry/messages': typeof EnquiryMessagesRoute
  '/enquiry/profile': typeof EnquiryProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/enquiry/members/$id': typeof EnquiryMembersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/bank-executive': typeof BankExecutiveRoute
  '/branches': typeof BranchesRoute
  '/contact': typeof ContactRoute
  '/contacts': typeof ContactsRoute
  '/enquiry': typeof EnquiryRoute
  '/loan-services': typeof LoanServicesRoute
  '/offers': typeof OffersRoute
  '/office': typeof OfficeRoute
  '/opportunities': typeof OpportunitiesRoute
  '/payment': typeof PaymentRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/network-admin': typeof AuthenticatedNetworkAdminRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/enquiry_/messages': typeof EnquiryMessagesRoute
  '/enquiry_/profile': typeof EnquiryProfileRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/enquiry_/members/$id': typeof EnquiryMembersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bank-executive'
    | '/branches'
    | '/contact'
    | '/contacts'
    | '/enquiry'
    | '/loan-services'
    | '/offers'
    | '/office'
    | '/opportunities'
    | '/payment'
    | '/plans'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/leads'
    | '/network-admin'
    | '/subscription'
    | '/enquiry/messages'
    | '/enquiry/profile'
    | '/api/public/razorpay-webhook'
    | '/enquiry/members/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bank-executive'
    | '/branches'
    | '/contact'
    | '/contacts'
    | '/enquiry'
    | '/loan-services'
    | '/offers'
    | '/office'
    | '/opportunities'
    | '/payment'
    | '/plans'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/terms'
    | '/admin'
    | '/dashboard'
    | '/leads'
    | '/network-admin'
    | '/subscription'
    | '/enquiry/messages'
    | '/enquiry/profile'
    | '/api/public/razorpay-webhook'
    | '/enquiry/members/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/bank-executive'
    | '/branches'
    | '/contact'
    | '/contacts'
    | '/enquiry'
    | '/loan-services'
    | '/offers'
    | '/office'
    | '/opportunities'
    | '/payment'
    | '/plans'
    | '/privacy'
    | '/refund'
    | '/services'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/network-admin'
    | '/_authenticated/subscription'
    | '/enquiry_/messages'
    | '/enquiry_/profile'
    | '/api/public/razorpay-webhook'
    | '/enquiry_/members/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BankExecutiveRoute: typeof BankExecutiveRoute
  BranchesRoute: typeof BranchesRoute
  ContactRoute: typeof ContactRoute
  ContactsRoute: typeof ContactsRoute
  EnquiryRoute: typeof EnquiryRoute
  LoanServicesRoute: typeof LoanServicesRoute
  OffersRoute: typeof OffersRoute
  OfficeRoute: typeof OfficeRoute
  OpportunitiesRoute: typeof OpportunitiesRoute
  PaymentRoute: typeof PaymentRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  EnquiryMessagesRoute: typeof EnquiryMessagesRoute
  EnquiryProfileRoute: typeof EnquiryProfileRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  EnquiryMembersIdRoute: typeof EnquiryMembersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-executive': {
      id: '/bank-executive'
      path: '/bank-executive'
      fullPath: '/bank-executive'
      preLoaderRoute: typeof BankExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry': {
      id: '/enquiry'
      path: '/enquiry'
      fullPath: '/enquiry'
      preLoaderRoute: typeof EnquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-services': {
      id: '/loan-services'
      path: '/loan-services'
      fullPath: '/loan-services'
      preLoaderRoute: typeof LoanServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities': {
      id: '/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof OpportunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network-admin': {
      id: '/_authenticated/network-admin'
      path: '/network-admin'
      fullPath: '/network-admin'
      preLoaderRoute: typeof AuthenticatedNetworkAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/enquiry_/messages': {
      id: '/enquiry_/messages'
      path: '/enquiry/messages'
      fullPath: '/enquiry/messages'
      preLoaderRoute: typeof EnquiryMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry_/profile': {
      id: '/enquiry_/profile'
      path: '/enquiry/profile'
      fullPath: '/enquiry/profile'
      preLoaderRoute: typeof EnquiryProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enquiry_/members/$id': {
      id: '/enquiry_/members/$id'
      path: '/enquiry/members/$id'
      fullPath: '/enquiry/members/$id'
      preLoaderRoute: typeof EnquiryMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNetworkAdminRoute: typeof AuthenticatedNetworkAdminRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNetworkAdminRoute: AuthenticatedNetworkAdminRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BankExecutiveRoute: BankExecutiveRoute,
  BranchesRoute: BranchesRoute,
  ContactRoute: ContactRoute,
  ContactsRoute: ContactsRoute,
  EnquiryRoute: EnquiryRoute,
  LoanServicesRoute: LoanServicesRoute,
  OffersRoute: OffersRoute,
  OfficeRoute: OfficeRoute,
  OpportunitiesRoute: OpportunitiesRoute,
  PaymentRoute: PaymentRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  EnquiryMessagesRoute: EnquiryMessagesRoute,
  EnquiryProfileRoute: EnquiryProfileRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  EnquiryMembersIdRoute: EnquiryMembersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
